apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: baremetalhost-sample
spec:
  # Add fields here
  foo: bar
  # Network configuration using attachment if Ironic networking enabled (optional)
  networkInterfaces:
  - name: ens3f0
    hostNetworkAttachment:
      name: mgmt-access-config
  - name: ens3f1
    hostNetworkAttachment:
      name: storage-trunk-config
